// react/todd-app-redux/src/component/todoItem.js
import React from 'react'
import { connect } from 'react-redux'

function TodoItem(props) {
    // console.log(props)
        return (
            <div className='todoitem'>
                <input type='checkbox' checked={props.todo.state} onClick={() => props.changeState(props.idx)}/>
                <input value={props.todo.content} />
                <button onClick={() => props.delItem(props.idx)}> - </button>
            </div>
        )
}
function mapStateToProps(state) {
    return {}
}

function mapDispatchToProps(dispatch) {
    return {
        delItem: (idx) => dispatch({ type: 'DEL_ITEM', idx }),
        changeState: (idx) => dispatch({ type: 'CHANGE_STATE', idx })
    }
}

export default connect(mapStateToProps, mapDispatchToProps)(TodoItem)

// vue/todo/src/components/todoItem.vue
<template>
<div>
    <input class="a" type="checkbox" :checked='item.state' @click='changeState'>
    <input type="text" :value='item.content'>
    <button @click='delItem'> - </button>
    {{a}}
</div>
</template>

<script>
export default {
 props:['item','index'],
 data() {
   return {
     a:'checkbox'
   }
 },
 methods: {
  delItem(){
    this.$emit('delItem',this.index)
    // console.log(this.index)
  },
  changeState(){
    this.$emit('changeState',this.index)
  }
},

}
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>

</style>
